### PR TITLE
Closes #463

### LINKED ISSUE #463: No way to build without --release?
Hi guys :wave: Is it me or it's only possible to `neon build --release`?
If I run just `neon build` then I get this message `Neon only build with --release...`. What is the reason of that?

There are some conditional attributes in my code that depend on `debug_assertions`, so those don't work because of this. 

Response would be greatly appreciated, especially if soon.

### PR DESCRIPTION
**Pull request by anurbol**

### CODE REVIEW

**Comment by kjvalencik** [comment]
CI is configured to run tests in release mode. Do you mind `cd`ing into `tests/dynamic`, performing a neon build _without_ release and then running `npm test`?

**Comment by anurbol** [comment]
@kjvalencik Of course, I'll inform you when done

**Comment by anurbol** [comment]
Uhm, I am sorry for stupid questions, should I run cargo build in the neon folder (that contains `cli`, `dev`, `src`, `dev` folders), and then run npm test in `tests/dynamic`?

**Comment by anurbol** [comment]
When I run `npm install` in `tests/dynamic`, npm tries to execute `install` script from package.json and that script tries to run `node ../../cli/bin/cli.js build --release`, but the `cli.js` file tries to require `../lib/cli.js`, but there is no `bin/lib` folder. I am not sure what's going on...

**Comment by anurbol** [comment]
But now I got `spawn cargo ENOENT`. But I do have cargo installed. The heck

**Pull request closed without merging**
