### PR TITLE
Support Node 10

### PR DESCRIPTION
**Pull request by mhsjlw**
Alright, a few things:

1. Pretty much no idea what I'm doing, I tried to look for developer documentation but found none
2. Haven't tested this with any other version than Node v10.1.0
3. I ran the test suite and everything passed

On paper, it looks like it works. I'm not entirely sure if there is a case where you are `::Cast()`ing a non-function.

Please let me know if I need to and how to implement backwards compatibility with this, also see #305 for a little more background information and how I got to this.

### CODE REVIEW

**Comment by mhsjlw** [comment]
@pitaj Good idea, it has been added. This is a quick way for me to ensure that my changes work across versions as well (I doubt it will)

**Comment by pitaj** [comment]
@dherman any chance of looking at this? It doesn't require an RFC does it?

**Comment by kjvalencik** [comment]
I don't think this is safe because the data might not actually be a callee. Should this code be removed or at least feature flagged for future removal?

**Comment by mhsjlw** [comment]
Based on this documentation: https://github.com/neon-bindings/neon/blob/b83ab66a442cc2b26fae7dc9227919be1d11a705/crates/neon-runtime/src/call.rs#L28, when would it ever not be the callee?

Additionally, I do not believe that this is the optimal solution, it just just the solution that I immediately know of that fixes this issue. Suggestions are appreciated, removal might not be needed.

**Comment by dherman** [comment]
@kjvalencik I've been googling around and haven't found a ton of recent discussions of this removal from the V8 API. In 2015 there was [this conversation](https://groups.google.com/forum/#!topic/v8-users/n5UFkh26dX4), but then they seemed like they were backtracking because of Node plugins, so I'm not sure what led them to decide it was OK to remove after all. Looking at the [V8 API changes doc](https://docs.google.com/document/d/1g8JFi8T_oAE_7uAri7Njtig7fKaPDfotU6huOa1alds/edit) just lists it as a removal but without links to any discussion, and the [commit](https://chromium-review.googlesource.com/c/v8/v8/+/741600) just has a one-line mention of why it's helpful for the V8 implementation.

I wonder if anyone knows of a discussion that led people to feel this was not a commonly-used feature. I'm leaning towards just removing it from Neon since that's what V8 is doing anyway, and it's not supported in N-API.

**Comment by dherman** [comment]
Thank you for the informative comment, as always!

> I doubt it's necessary, though. Node's citgm project has pretty good coverage of native modules and none that I know of broke due the removal of the `Callee()` method.

Yeah, I think we should avoid providing primitives beyond what V8 and N-API provide, so I'm going to propose we just cut `callee()` for 0.2.

**Comment by dherman** [comment]
@mhsjlw Thank you so much for getting the ball rolling with this PR! I ended up submitting the separate PR #314, but I wouldn't have gotten there without your contribution here!

**Comment by mhsjlw** [comment]
Great to have helped! Is there a release on the horizon?

**Pull request closed without merging**
