### PR TITLE
Windows electron

### PR DESCRIPTION
**Pull request by kjvalencik**
Fixes https://github.com/neon-bindings/neon/issues/399
Fixes https://github.com/neon-bindings/neon/issues/389
Fixes https://github.com/neon-bindings/neon/issues/394
Fixes https://github.com/neon-bindings/neon/issues/194

Replaces https://github.com/neon-bindings/neon/pull/404

### CODE REVIEW

**Comment by joshuef** [comment]
This is working well on windows 10 w/  https://github.com/joshuef/safe-nodejs in the [safe browser](https://github.com/maidsafe/safe_browser) 🎉

**Comment by joshuef** [comment]
Total side note, but for testing electron apps, I'd hiiighly recommend [testcafe](https://devexpress.github.io/testcafe/documentation/getting-started/) over spectron. I've found it to be wayyyy more stable and easier to use too!

**Comment by marcmo** [comment]
Hello @kjvalencik , great to hear you fixed some issues on Windows and Linux. we are experiencing some of those issues. any plans when you want to include these fixes in a neon release?
I tried including all the neon crates from master but couldn't build anymore so I guess everything has to match up.

**Comment by kjvalencik** [comment]
@marcmo Yes, they all need to be inline. We are in the process of merging a fairly large PR that is the prep work for N-API.

I will cut a release later this week after that lands. Thanks for your patience!

**Comment by terryzhao** [comment]
> @marcmo Yes, they all need to be inline. We are in the process of merging a fairly large PR that is the prep work for N-API.
> 
> I will cut a release later this week after that lands. Thanks for your patience!

Hello @kjvalencik Have you distribute this release to npm ?

**Comment by terryzhao** [comment]
> @marcmo Yes, they all need to be inline. We are in the process of merging a fairly large PR that is the prep work for N-API.
> 
> I will cut a release later this week after that lands. Thanks for your patience!

Hello @kjvalencik  Glad to hear that you will publish this release.  I'm waiting for this release so eagerly!:smile:

**Pull request merged**
