### PR TITLE
cslice: make #![no_std]

### PR DESCRIPTION
**Pull request by whitequark**
No change other than the annotation and updating the `use`s.

Once this is merged can I get a release of cslice, please?

### CODE REVIEW

**Comment by dherman** [comment]
Doh! I was just in the process of moving cslice to https://github.com/dherman/cslice and didn't see this PR. Do you mind re-filing it there? I'll be happy to merge and publish ASAP.

**Comment by dherman** [comment]
Never mind, I submitted dherman/cslice#2 and set the author to you :)

**Comment by dherman** [comment]
I've published cslice 0.3.0 with your changes. Thanks!

**Comment by whitequark** [comment]
Thanks!

**Pull request closed without merging**
