### PR TITLE
Windows npm issues

### PR DESCRIPTION
**Pull request by dherman**
(Pulled out from #122.)

### CODE REVIEW

**Comment by jedireza** [comment]
r+ to the changes, they're simple enough.

I wonder what we lose by adding `--silent`? At first glance this sounds like a bug that should be filed up-streamed. If we get around this using `--silent` do we want to create an issue that tracks this and removes the argument when it's not required?

**Comment by jedireza** [comment]
I see now that the output of cargo build scripts are suppressed anyways, unless an error occurs.

 - https://github.com/rust-lang/cargo/issues/1106

There is a `-vv` argument (possibly undocumented) we can pass to cargo to see the output of the build script while it's running.

 - https://github.com/rust-lang/cargo/pull/2630

This can be helpful in the case of windows builds hanging since an error hasn't actually occurred yet (hanging process). With this I'm able to get more insight into what's causing the hang (possibly something related to `$ node-gyp rebuild`).

**Comment by dherman** [comment]
OK, it took a while but the bug has been identified in Rust's `Command` API, and a PR has been filed:

https://github.com/rust-lang/rust/pull/38835

So we should just go ahead with the workaround but leave a comment to remove the workaround once the Rust fix has been in long enough. We may want to wait at least a couple of Rust release cycles so people can use older Rusts.

**Pull request merged**
