### PR TITLE
Document lldb usage and some v8 constructs.

### PR DESCRIPTION
**Pull request by winding-lines**
Let me know if you find these useful, or need more editing.

### CODE REVIEW

**Comment by jedireza** [comment]
Thanks for creating this PR. I didn't see this before #130 landed.

As you're probably aware, the GitHub organization and domain name have changed to `neon-bindings` and `neon-bindings.com`. When we made that switch we had to setup hosting and publishing again. Luckily, publishing is automated, so once changes land, they'll show up after a successful Travis build.

The `neon-bindings/www` repo has the website (https://www.neon-bindings.com/) files and the crate docs (https://docs.neon-bindings.com/) are published from the `gh-pages` branch of this repo (`neon-bindings/neon`).

We still need to move the content from `./docs` to the `neon-bindings/www` repo (exactly how hasn't been decided). But I think that's the same place we should host the lldb content you wrote here, so maybe we should create an issue and/or PR on that repo. 

If you'd like to update this PR (or create a new one) with the content you have for the `neon-sys::raw` module, I'd like to change the v8 doc links to use the NodeSource domain instead of Paul's.

**Comment by winding-lines** [comment]
@jedireza I would love to move over the lldb information. A lot of it is neon/node specific. I will tentatively create under a neon folder, unless you have a better idea :)

**Comment by jedireza** [comment]
I see the new PR over at `neon/www`, thanks. Should we close this PR or do you plan on updating updating it for the crate docs?

**Comment by winding-lines** [comment]
We should close this PR, thanks!

Marius
---

**Pull request closed without merging**
