### PR TITLE
Add FreeBSD

### PR DESCRIPTION
**Pull request by MikaelUrankar**

### CODE REVIEW

**Comment by MikaelUrankar** [comment]
Your CI seems broken

**Comment by kjvalencik** [comment]
This looks good, but FYI, this is updating the legacy backend which is deprecated and will be removed in 1.0. Is there a reason your project is unable to move to the Node-API backend?

Concerning CI, only Windows is broken. There is a fix in another PR that I haven't cherry picked. It broke when GitHub upgraded the Windows runners. Unfortunately, the legacy backend is very sensitive to versions.

**Comment by MikaelUrankar** [comment]
> This looks good, but FYI, this is updating the legacy backend which is deprecated and will be removed in 1.0. Is there a reason your project is unable to move to the Node-API backend?

It's not my project, signal-desktop uses this crate: https://github.com/signalapp/ringrtc/blob/master/src/rust/Cargo.toml#L59

**Comment by kjvalencik** [comment]
Thanks for the info!

**Pull request merged**
